services:
  mongodb:
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: social_events
    volumes:
      - mongo_data:/data/db
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  mongo_data:
    driver: local
